# Docker-Compose file for Stockholm Network
version: '3'

services:
  dns:
    container_name: ${COMPOSE_PROJECT_NAME}_dns_server
    hostname: ${COMPOSE_PROJECT_NAME}_dns_server
    restart: always
    build:
      context: ./dns
      args:
        - DNS_SERVER_IP=${DNS_VLAN1}
        - VLAN_DOMAIN=${VLAN_DOMAIN}
        - FORWARDER=${FORWARDER}
        - OPENVPN_VLAN1=${OPENVPN_VLAN1}
        - DB_VLAN1=${DB_VLAN1}
    networks:
      sto_vlan1:
        ipv4_address: ${DNS_VLAN1}
    volumes:
      - "./dns/log:/var/log/named"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 53:53/udp

  openvpn_server:
    container_name: ${COMPOSE_PROJECT_NAME}_openvpn_server
    hostname: ${COMPOSE_PROJECT_NAME}_openvpn_server
    restart: always
    cap_add:
      - "NET_ADMIN"
    dns:
      - ${DNS_VLAN1}
    build:
      context: ./openvpn
      args:
        - VLAN_VPN_CLIENTS_SUBNET=${VLAN_VPN_CLIENTS_SUBNET}
        - DNS_SERVER_IP=${DNS_VLAN1}
    networks:
       sto_vlan1:
        ipv4_address: ${OPENVPN_VLAN1}
    ports:
      - "1194:1194/udp"
    volumes:
      - "./openvpn/data/logs:/etc/openvpn/logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  radius_server:
    container_name: ${COMPOSE_PROJECT_NAME}_radius
    hostname: ${COMPOSE_PROJECT_NAME}_radius
    restart: always
    dns:
      - ${DNS_VLAN1}
    build:
      context: ./radius
      args:
        - DB_VLAN1=${DB_VLAN1}
        - RADIUS_USR_PASSWORD=${RADIUS_USR_PASSWORD}
        - REALM=${RADIUS_REALM}
        - RADIUS_SECRET=${RADIUS_SECRET}
    networks:
      sto_vlan1:
        ipv4_address: ${RADIUS_VLAN1}
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./radius/logs:/var/log/radius
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - mysql_db:database
    depends_on:
      - "mysql_db"

  mysql_db:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    hostname: mysql.acme.com
    restart: always
    dns:
      - ${DNS_VLAN1}
    build:
      context: ./mysql
      args:
        - DB_VLAN1=${DB_VLAN1}
        - MYSQL_CONTAINER_USER=mysql
        - MYSQL_CONTAINER_GROUP=mysql
        - MYSQL_DATA_DIR=${MYSQL_DATA_DIR}
        - MYSQL_LOG_DIR=${MYSQL_LOG_DIR}
        - RADIUS_USR_PASSWORD=${RADIUS_USR_PASSWORD}
        - RADIUS_VLAN1=${RADIUS_VLAN1}
    networks:
      sto_vlan1:
        ipv4_address: ${DB_VLAN1}
    volumes:
      - ./mysql/data:${MYSQL_DATA_DIR}
      - ./mysql/log/:${MYSQL_LOG_DIR}
      # TODO FIX LOCALTIME IN MYSQL CONTAINER
      #- "/etc/timezone:/etc/timezone:ro"
      #- "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_CONTAINER_USER: "mysql"
      MYSQL_CONTAINER_GROUP: "mysql"
      MYSQL_DATABASE: "radius"

  suricata:
    build:
      context: ./ids
    container_name: ${COMPOSE_PROJECT_NAME}_suricata
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./ids/logs/:/var/log/suricata
  #    - ./ids/rules/my.rules:/var/lib/suricata/rules/my.rules
    entrypoint: /entrypoint.sh
  
  elk:
    container_name:  ${COMPOSE_PROJECT_NAME}_elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

networks:
  sto_vlan1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${VLAN1_SUBNET}
  #sto_vlan2:
  #  driver: bridge
  #  ipam:
  #    driver: default
  #    config:
  #      - subnet: ${VLAN2_SUBNET}